name = "FVADE"
uuid = "5d501bba-b699-476a-a68f-26d2e41c9b5c"
authors = ["David Gomez-Castro <david@gomezcastro.xyz>"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ForwardDiff = "1.0.1"
JLD2 = "0.5.12"
JuliaFormatter = "2.1.1"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
LinearSolve = "3.7.2"
NonlinearSolve = "4.5.1"
Plots = "1.40.12"
ProgressMeter = "1.10.4"
QuadGK = "2.11.2"
SpecialFunctions = "2.5.1"
Test = "1.11.0"
